import { runPipeline, AdaError } from '@ada/core';
import { loadConfig } from '../config.js';
import { emit, emitError, type OutputFormat } from '../output.js';
import { buildPipelineDeps } from '../wire.js';

export interface ComposeOptions {
  url?: string;
  config?: string;
  output?: string;
  template?: string;
  outputFormat: OutputFormat;
}

export async function composeCommand(options: ComposeOptions): Promise<number> {
  try {
    const config = loadConfig({
      ...(options.config !== undefined ? { configPath: options.config } : {}),
      ...(options.url !== undefined ? { url: options.url } : {}),
      ...(options.output !== undefined ? { output: options.output } : {}),
      ...(options.template !== undefined ? { template: options.template } : {}),
    });

    const { deps, providerSink } = buildPipelineDeps(config);
    // P1: `compose` runs the same pipeline as `run` — the difference is that
    // the caller can stop after composition.html is generated by setting a
    // bogus output path. We keep behaviour symmetric for now; richer
    // "stop-before-render" mode is P2.
    const report = await runPipeline(config, deps, { eventSink: providerSink });
    emit(
      options.outputFormat,
      report,
      `Composition générée → ${report.outputPath ?? '(no output)'}`,
    );
    return report.status === 'success' ? 0 : 2;
  } catch (err) {
    if (err instanceof AdaError) {
      emitError(options.outputFormat, err.code, err.message);
      return err.code === 'E_CONFIG' ? 1 : 2;
    }
    emitError(options.outputFormat, 'E_RUNTIME', (err as Error).message);
    return 2;
  }
}
